sudo: false

services:
  - docker
  
language: python

python:
  - 2.7

install:
  - sudo docker info
  - docker pull jenkins
  

before_install:
  - pip install boto3
  - pip install pip --upgrade
  - pip install awscli --upgrade
  - pip install requests --upgrade
  - pip install argparse --upgrade
  - sudo service docker stop
  - sudo nohup docker daemon -H tcp://0.0.0.0:2375 -H unix:///var/run/docker.sock &

script:
  - docker pull ubuntu
  - docker images |grep jenkins
  - docker images |grep ubuntu
