sudo: false

services:
  - docker
  
language: python

python:
  - 2.7

install:
  - docker pull jenkins

script:
  - docker pull ubuntu
  - docker images |grep jenkins
  - docker images |grep ubuntu
