sudo: false

services:
  - docker
  
language: python

python:
  - 2.7

install:
  - docker pull jenkins
  

before_install:
  - pip install boto3
  - pip install pip --upgrade
  - pip install awscli --upgrade
  - pip install requests --upgrade
  - pip install argparse --upgrade

script:
  - docker pull ubuntu
  - docker images |grep jenkins
  - docker images |grep ubuntu
